config/routes.rb
Rails.application.routes.draw do
  sso_routes
  resources :subscribes
  resources :users

  root "topics#index"
  # resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :topics do
    resources :messages, only: [:index, :new, :create]
  end
  resources :messages, only: [:show, :edit, :update, :destroy]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :topic
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :set_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all
  end

   def show
     #@topic = Topic.find(params[:topic_id])
     #@message = @topic.messages.find(params[:id])
   end

  def new
    @message = Message.new
  end

  def edit
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @message = @topic.messages.create(message_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to topic_path(@topic), notice: '添加message成功' }
        format.js
        format.json { render json: @message, status: :created, location: @topic }
      else
        @errors = @message.errors.full_messages
        # require "pry";binding.pry;
        format.html { redirect_to topic_path(@topic), notice: '添加message失败，请检查标题和内容是否正确' }
        format.js
        format.json { render json: @message.errors, status: :unprocessable_entity, location: @topic}
        # format.json { render json: @message.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
   respond_to do |format|
     if @message.update(message_params)
       format.html { redirect_to @message, notice: 'Message was successfully updated.' }
       format.json { render :show, status: :ok, location: @topic }
     else
       format.html { render :edit }
       format.json { render json: @message.errors, status: :unprocessable_entity }
     end
   end
  end

  def destroy
    @message.destroy
    redirect_to topic_path(@message.topic)
  end

  private

  def message_params
    params.require(:message).permit(:title, :content)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params[:id])
  end


end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for([@topic, @topic.messages.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/messages/_message.html.erb
<p>
  <strong>Title:</strong>
  <%= message.title %>

  <br>
  <strong>Content:</strong>
  <%= message.content %>
  <br>
</p>

<p>
  <%= link_to 'Show', message %> |
  <%= link_to 'Edit', edit_message_path(message) %> |
  <%= link_to 'Destroy', message,
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/messages/create.js.erb
<% if @errors %>
  <% if @errors.to_s.include?"必须有标题" %>
    alert('添加失败：必须有标题');
  <% elsif @errors.to_s.include?"标题必须唯一"%>
    alert('添加失败：该标题已经存在');
  <% elsif @errors.to_s.include?"必须有内容"  %>
    alert('添加失败：必须有内容');
  <% else %>
    alert('添加失败：未知错误');
  <% end %>
<% else %>
  $("<%= escape_javascript(render @message) %>").appendTo("#messages");
  $('#message_title').val('');
  $('#message_content').val('');
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>
<%#= render 'form', Message:@message %>
<!--<p>标题：<%#@message.title%></p>-->

<%= form_for @message, url: {action: "update"} do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content, cols: 120, rows: 10 %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%#= link_to 'Show', @message %>
<%#= link_to 'Back', topic_path(@topic) %>

app/views/messages/index.html.erb
<h2>Messages</h2>
<%= render @topic.messages %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<br>

<!--<h2>Messages</h2>-->
<%#= render 'message', Message: @message %>


<p>
  <strong>Title:</strong>
  <%= @message.title %>

  <br>
  <br>

  <strong>Content:</strong>
  <%= @message.content %>
  <br>
</p>


<br>


<!--<%#= link_to 'Edit', edit_topic_message_path([message.topic, message]) %> |-->
<%#= link_to 'Back', topic_path(@topic) %>