config/routes.rb
Rails.application.routes.draw do
  sso_routes
  resources :subscribes
  resources :users

  root "topics#index"
  # resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :topics do
    resources :messages, only: [:index, :new, :create]
  end
  resources :messages, only: [:show, :edit, :update, :destroy]
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :subscribes, dependent: :destroy
  validates :topic_name, presence: true

  before_destroy :ensure_not_referenced_by_any_subscribe

  private

  # 确保没有订阅仍在引用该主题
  def ensure_not_referenced_by_any_subscribe
    unless subscribes.empty?
      errors.add(:base, 'Subscribes present')
      throw :abort
    end
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:topic_name)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :topic_name %>
    <%= form.text_field :topic_name, id: :topic_topic_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>
<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Topic name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.topic_name %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<!--        # ???????-->
        <% if Subscribe.where("user_id = ? AND topic_id = ?", session[:current_user_id], topic.id).exists? %>
          <% sub_id = Subscribe.where("user_id = ? AND topic_id = ?", session[:current_user_id], topic.id).pluck(:id) %>
<!--          <td><%#= button_to '取消订阅', subscribe_path(id:sub_id), method: :delete, data: { confirm: "Are you sure?" } %></td>-->
          <td><%= button_to '取消订阅', subscribe_path(id:sub_id), method: :delete, data: { confirm: "Are you sure?" } %></td>
<!--          <td><%#= sub_id %></td>-->
        <% else %>
          <td><%= button_to '订阅', subscribes_path(topic_id:topic) %></td>
      <% end  %>
      </tr>
    <% end %>
  </tbody>
</table>

<p>
  <%= link_to ("current_user_id: #{session[:current_user_id]}"), user_path(id:session[:current_user_id])  %>
</p>
<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h1>Topic name: <%= @topic.topic_name %></h1>
</p>

<br>

<h2>Messages</h2>

<%= render @topic.messages %>
<p id="messages">
  <% if @errors %>
    <font><%= @errors %></font>
  <% end %>
</p>

<br>

<h2>Add a message:</h2>
<%= render 'messages/form' %>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>