config/routes.rb
Rails.application.routes.draw do
  sso_routes
  resources :subscribes
  resources :users

  root "topics#index"
  # resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :topics do
    resources :messages, only: [:index, :new, :create]
  end
  resources :messages, only: [:show, :edit, :update, :destroy]
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  validates :user_id, uniqueness: {scope: :topic_id, message: "已订阅该主题"}
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController

  ## 新建订阅前先设置用户id（找不到user_id即新建user）
  # include CurrentUser
  # before_action :set_user, only: [:create]

  before_action :set_subscribe, only: [:show, :edit, :update, :destroy]

  # GET /subscribes
  # GET /subscribes.json
  def index
    @subscribes = Subscribe.all
  end

  # GET /subscribes/1
  # GET /subscribes/1.json
  def show
  end

  # GET /subscribes/new
  def new
    @subscribe = Subscribe.new
  end

  # GET /subscribes/1/edit
  def edit
  end

  # POST /subscribes
  # POST /subscribes.json
  def create
    topic = Topic.find(params[:topic_id])
    # test 每次订阅 都加到 user_id 为1的用户
    # @user = User.find(1)
    set_user
    @subscribe = @user.subscribes.build(topic: topic)

    respond_to do |format|
      if @subscribe.save
        ## 这里跳到了users show界面
        format.html { redirect_to @subscribe.user, notice: '添加订阅成功' }
        format.json { render :show, status: :created, location: @subscribe }
      else
        format.html { render :new }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscribes/1
  # PATCH/PUT /subscribes/1.json
  def update
    respond_to do |format|
      if @subscribe.update(subscribe_params)
        format.html { redirect_to @subscribe, notice: 'Subscribe was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscribe }
      else
        format.html { render :edit }
        format.json { render json: @subscribe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscribes/1
  # DELETE /subscribes/1.json
  def destroy
    @subscribe.destroy
    respond_to do |format|
      # format.html { redirect_to subscribes_url, notice: 'Subscribe was successfully destroyed.' }
      format.html { redirect_to @subscribe.user, notice: '取消订阅成功' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscribe
      @subscribe = Subscribe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscribe_params
      params.require(:subscribe).permit(:topic_id, :user_id)
      # params.require(:subscribe).permit(:is_mail, :is_message, :topic_id, :user_id)
    end

    def set_user
      @user = User.find(session[:current_user_id])
    end
end

app/helpers/subscribe/s_helper.rb
module Subscribe::SHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/subscribes/_form.html.erb
<%= form_with(model: subscribe, local: true) do |form| %>
  <% if subscribe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subscribe.errors.count, "error") %> prohibited this subscribe from being saved:</h2>

      <ul>
      <% subscribe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :is_mail %>
    <%= form.check_box :is_mail, id: :subscribe_is_mail %>
  </div>

  <div class="field">
    <%= form.label :is_message %>
    <%= form.check_box :is_message, id: :subscribe_is_message %>
  </div>

  <div class="field">
    <%= form.label :topic_id %>
    <%= form.text_field :topic_id, id: :subscribe_topic_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :subscribe_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subscribes/edit.html.erb
<h1>Editing Subscribe</h1>

<%= render 'form', subscribe: @subscribe %>

<%= link_to 'Show', @subscribe %> |
<%= link_to 'Back', subscribes_path %>

app/views/subscribes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subscribes</h1>

<table>
  <thead>
    <tr>
      <th>Is mail</th>
      <th>Is message</th>
      <th>Topic</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscribes.each do |subscribe| %>
      <tr>
        <td><%= subscribe.is_mail %></td>
        <td><%= subscribe.is_message %></td>
        <td><%= subscribe.topic.topic_name %></td>
        <td><%= subscribe.user.username %></td>
        <td><%= link_to 'Show', subscribe %></td>
        <td><%= link_to 'Edit', edit_subscribe_path(subscribe) %></td>
        <td><%= link_to 'Destroy', subscribe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscribe', new_subscribe_path %>

app/views/subscribes/new.html.erb
<h1>New Subscribe</h1>

<%= render 'form', subscribe: @subscribe %>

<%= link_to 'Back', subscribes_path %>

app/views/subscribes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Is mail:</strong>
  <%= @subscribe.is_mail %>
</p>

<p>
  <strong>Is message:</strong>
  <%= @subscribe.is_message %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @subscribe.topic.topic_name %>
</p>

<p>
  <strong>User:</strong>
  <%= @subscribe.user.username %>
</p>

<%= link_to 'Edit', edit_subscribe_path(@subscribe) %> |
<%= link_to 'Back', subscribes_path %>